# Site settings
title: XieYiWen
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xieyiwen.github.io"

# User settings
username: Xie YiWen
user_description: I'm a Software Engineer, 5+ years gopher. Professional skills includes Blockchain, Golang, Kubernetes, Solidity, etc.
user_title: Software Engineer,Gopher,BlockChain Engineer
email: wsxieyiwen@gmail.com
github_username:  xieyiwen

timezone: Asia/Shanghai
encoding: "utf-8"
location: Shanghai, China
permalink: /:year/:month/:day/:title/

exclude: ['package.json', 'src' , 'node_modules']
github:
  repository_url: https://github.com/xieyiwen/xieyiwen.github.io
google:
  analytics_id: G-6KHZGKR6WE